### ISSUE TITLE
[Enhancement]: Add support for two-finger panning on chart

### ISSUE THREAD

**Issue by benwolski** [CrocSwap/ambient-ts-app#2608]
### Requirements

Like [Tradingview](https://www.tradingview.com/chart/I5aQ8xYr/?symbol=BITSTAMP%3ABTCUSD), the user should be able to pan to the left (i.e. back in time) using a two-finger swipe gesture while the cursor is over a chart.

### Assumptions

The default browser navigation response to the two-finger swipe left/right gesture can be disabled and the chart can respond to the gesture with the same scroll function as currently implemented when the user holds the option(mac) or command(windows) button while scrolling with a mouse scroll wheel or two fingers up/down on touchpad (i.e. pan/scroll back in time) without changing y-axis scale.

**Comment by enwong10** [comment]
Caused by two finger zoom being registered as a WheelEvent - current behaviour is written for mouse scroll (and only up and down). 

Worth noting that many many many events are fired (for every pixel that's moved, rather than for every scroll wheel) when scrolling with two fingers on trackpad, will likely need a debounce of some kind if we want to standardize trackpad behaviour. 

No easy way to differentiate between two-finger trackpad and mousewheel has been found yet. Needs more investigating
