### ISSUE TITLE
[Tech Debt]: Rate Limiting for Infura RPC

### ISSUE THREAD

**Issue by PaulMcInnis** [CrocSwap/ambient-ts-app#2678]
### What is needed?

Currently it's possible to make many many RPC calls / second, given a failing useEffect chain or other bug.

We should safeguard against this by adding rate limiting FE-side.

Low prio since we have a high cap on infura calls rn.

**Comment by PaulMcInnis** [comment]
saw this again, thousands of requests in under 30 seconds when modifying a useEffect in the chart. locked out by infura again, huge nuisance.

**Comment by enwong10** [comment]
Escalating due to infura outages occurring more frequently

**Comment by enwong10** [comment]
Notes: 
- ~115 infura calls on load 
  - over 50% (~65) of those are looking up ENS addresses
  - @benwolski mentioned that this used to be done via graph cache server, but was deprecated 
- a handful (< 5) of calls per new block
  - fetch pool liquidity, query spot price... confirmed with Ben that this is expected behaviour 

Recommendations: 
- Cache ENS addresses in the BE server, only fetch from infura as necessary

cc: @Mister-Meeseeks @JustinGirard

**Comment by enwong10** [comment]
Closing in favour of #2929
