### ISSUE TITLE
[Bug]:  Token Selectors with correct token icons show fallback token icons on load

### ISSUE THREAD

**Issue by surudhb** [CrocSwap/ambient-ts-app#2761]
### What happened?

- actual token icons appear for half a second and then are replaced by the fallback token icon (even when the proper icon exists)

### How?

- close any windows with the following url https://develop--ambient-finance.netlify.app/trade/market/chain=0x5&tokenA=0x0000000000000000000000000000000000000000&tokenB=0x630f8b9d8f517af8f5b8670e6a167b6c0240d583
- open up this url (try incognito) https://develop--ambient-finance.netlify.app/trade/market/chain=0x5&tokenA=0x0000000000000000000000000000000000000000&tokenB=0x630f8b9d8f517af8f5b8670e6a167b6c0240d583

### What was Expected?

correct token icons

**Comment by emilydrakesmith** [comment]
The app loads token logos with react suspense and the `<NoTokenIcon />` element is used as a placeholder until the fetch completes. This helps the DOM load more quickly and content doesn't "jump" as fetch requests complete and the resultant images are patched into the DOM by react's differencing library.

We can change the placeholder icon to something else if desired but the functionality as described is intentional.

![image](https://github.com/CrocSwap/ambient-ts-app/assets/71150790/7bfced25-b247-45b8-85d9-e6120f9df170)

**Comment by surudhb** [comment]
is the behaviour on an incognito window

**Comment by enwong10** [comment]
Unable to reproduce
